CREATE DATABASE traffic;

CREATE USER traffic_user WITH PASSWORD 'traffic_pass';
GRANT ALL PRIVILEGES ON DATABASE traffic TO traffic_user;
GRANT USAGE, CREATE ON SCHEMA public TO traffic_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO traffic_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO traffic_user;
